# Generated by Django 5.2.8 on 2026-08-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('request_body_hash', models.CharField(max_length=64)),
                ('request_body', models.JSONField()),
                ('response_body', models.JSONField()),
                ('status_code', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['idempotency_key'], name='payments_id_idempot_104db4_idx'), models.Index(fields=['created_at'], name='payments_id_created_5f2f3d_idx'), models.Index(fields=['expires_at'], name='payments_id_expires_691ca7_idx')],
            },
        ),
        migrations.CreateModel(
            name='InFlightLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['idempotency_key'], name='payments_in_idempot_e9cb6f_idx'), models.Index(fields=['expires_at'], name='payments_in_expires_2900af_idx')],
            },
        ),
    ]
